### PR TITLE
CSV Export Improvement

### PR DESCRIPTION
**Pull request by ais-one**
1. Allow other field delimiters to be used, rather than just double quote (")
2. Form the CSV such that there is no extra comma (,) at the end

### CODE REVIEW

**Comment by ais-one** [comment]
I have tested the code, hopefully this minor improvement can be included.

**Comment by lazymofo** [comment]
I might implement this, but I was wondering why this feature would be desired.

**Comment by ais-one** [comment]
Well, sometimes, I use the (') instead of (") because I directly use it for SQL in PHP

so I get, INSERT INTO abc VALUES ('a','b','c'), instead of INSERT INTO abc VALUES ("a","b","c") which will give me error.

The other thing is that the export file has extra comma (,) at the end, it may be cleaner or look nicer to not have the extra (,) ...

**Comment by lazymofo** [comment]
Functionality added. Doh, I realized I wasn't even even escaping the CSV correctly. CSV need a double-quote to escape a double-quote escaping, but you'll want to configure backslash escaping for your needs.

**Pull request closed without merging**
