### PR TITLE
country and language localization functionality

### PR DESCRIPTION
**Pull request by fcordeiro6**
Hello, my name is Fabio and I'm Brazilian.

Starting, excuses for poor English.

I'm use the LM class and it was necessary to translate all the mensangens. In this way I created a simple method for this purpose, with the possibility of a configuration file.

As an example I send the file to pt-br.

### CODE REVIEW

**Comment by raffaelj** [comment]
Hello Fabio,

I like the idea of localization possibilities and I already thought a view times about it. If the feature will be included in LM I would translate it into German, too.

One thing - if you didn't notice - your mysql password is still visible in the commit history. I suggest to change it instead of trying to delete the commit history.

I'm not sure, how much time I can spend the next days. But if you want we can work together on a cleaner solution. 

Some thoughts:

## localization / lazy_mofo.php

* For now LM can be included as one file without any other neccessary files and I'm not sure how the author feel about splitting it into multiple files.

* The variables with HTML inside should be split into one variable holding the translated word and one holding the HTML. With this behavior it's easyer to add custom changes.

* Localization isn't only about a view words and the date format. In Germany we use commas instead of dots for decimal numbers. As far as I explored the code this is only possible with a user defined function right now.

## config.inc.php

* In my setup (sorry, it's a private repo until I change a view things) I used two files. `config.ini.php` with my personal database entries and `config.ini.php.dist` with example login data and I added `*.ini.php` to my `.gitignore` to prevent my personal data from public committing.

**Comment by lazymofo** [comment]
Fabio and Raffael j,

Thanks for your code and help in adding internationalization/i18n!

This weekend I'll work on a template that you can populate according to
country + languange;

br_bp.php (brazil + brazilian portuguese)
de_de.php (detchland + deutsch)

Check back on later this weekend or Monday.

¡Obrigado e adeus!
Danke und auf Wiedersehen!

-Ian

**Comment by fcordeiro6** [comment]
Ian and Raffael,

 

1) Please, for Brazil, use: pt_br, like in html5. First language after country.

2) My time zone is GMT-3.  And yours?

3) I have more features that I'm developing. I want to work hard with you.

4) Later this weekend or Monday, we continue the work with your template.

 

Thank you, see you soon!
Danke und auf Wiedersehen!
Obrigado e até logo!  

 

Fabio Cordeiro
+55 11 99588-7933
fabio@2f.com.br

**Comment by lazymofo** [comment]
1. I changed the naming convention to language-country as you suggested.
That seems to be the standard.

2. I'm in timezone GMT-7.

3. I'm not very interested in adding features, but I will consider them.
Feel free to fork.

**Comment by raffaelj** [comment]
@ Ian: Thank you very much for your template. I sent a pull request with the German language file.

@ Fabio: Im in timezone GMT+2

@ all: Sorry for not answering for so many days. I had a lot to do and I caught a cold.

**Pull request closed without merging**
